include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    require_trailing_commas: true
    public_member_api_docs: false
    document_ignores: false
    lines_longer_than_80_chars: false
    discarded_futures: false
